# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "fetch-open"
client_id = "b50187b517382a154d52be0d7d11e5cb"
application_url = "https://agreements-org-guaranteed-composer.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_product_listings,read_products"

[auth]
redirect_urls = [
  "https://agreements-org-guaranteed-composer.trycloudflare.com/auth/callback",
  "https://agreements-org-guaranteed-composer.trycloudflare.com/auth/shopify/callback",
  "https://agreements-org-guaranteed-composer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-ongraph-data.myshopify.com"
