[[extensions]]
name = "Flow action 2"
type = "flow_action"
handle = "flow-action-2"
description = "Your description"
runtime_url = "https://url.com/api/execute"

[settings]

  [[settings.fields]]
  type = "customer_reference"
  required = true

  [[settings.fields]]
  type = "single_line_text_field"
  key = "your-field-key"
  name = "Display name"
  description = "A description of my field"
  required = true
